<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="venkay32" ignored="0" name="Timeout Test" tests="2" failures="1" timestamp="21 Oct 2019 13:48:26 GMT" time="15.459" errors="0">
  <testcase name="timeoutTestOne" time="3.012" classname="com.AdvancedTestNG.webdriver.TestNGTimeoutTest">
    <failure type="org.testng.internal.thread.ThreadTimeoutException" message="Method com.AdvancedTestNG.webdriver.TestNGTimeoutTest.timeoutTestOne() didn&amp;apos;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.AdvancedTestNG.webdriver.TestNGTimeoutTest.timeoutTestOne() didn't finish within the time-out 3000
at java.lang.Throwable.toString(Unknown Source)
at java.lang.Throwable.<init>(Unknown Source)
at java.lang.Exception.<init>(Unknown Source)
at java.lang.RuntimeException.<init>(Unknown Source)
at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 3 stack frames]]>
    </failure>
  </testcase> <!-- timeoutTestOne -->
  <testcase name="timeoutTestTwo" time="2.152" classname="com.AdvancedTestNG.webdriver.TestNGTimeoutTest"/>
</testsuite> <!-- Timeout Test -->
